Kyle/refresh redux
calblueprint/meepanyar pull request #47
Opened 2021-03-08 01:05 UTC by kyleqhua

[//]: # "These comments are meant for your reference. They are invisible and don't need to be deleted!"

# What's new in this PR
Refreshes site data every 15 minutes or when user goes from offline status to online.

[//]: # "Describe what's new in this PR in a few lines. A description and bullet points for specifics will suffice."

## How to review
Run locally. Change interval to 1 minute to easier test. Change airtable site data (like name). Wait for refresh. Can turn off internet status and back on to test it instataneously. When interval is low (1ish minute) there might be a 2 cycle delay between the airtable change and pulling of data.

[//]: # 'The order in which to review files and what to expect when testing locally'

## Relevant Links

### Online sources

[//]: # 'Optional - copy links to any tutorial or documentation that was useful to you when working on this PR'

### Related PRs

[//]: # "Optional - related PRs you're waiting on/ PRs that will conflict, etc; if this is a refactor, feel free to add PRs that previously modified this code"

## Next steps

[//]: # "What's NOT in this PR, doesn't work yet, and/or still needs to be done"

### Screenshots

[//]: # "Add screenshots of expected behavior - GIFs if you're feeling fancy!"

CC: @julianrkung

[//]: # 'This tags Julian as a default. Feel free to change, or add on anyone who you should be in on the conversation.'

2021-03-08 04:03 UTC, julianrkung requested changes
Did a quick sweep and made some comments!

2021-03-08 04:03 UTC, julianrkung commented on src/lib/airtable/request.js.rej
> +diff a/src/lib/airtable/request.js b/src/lib/airtable/request.js	(rejected hunks)
Remove this file from the PR.

2021-03-08 04:03 UTC, julianrkung commented on src/lib/airtable/schema.js.rej
> +diff a/src/lib/airtable/schema.js b/src/lib/airtable/schema.js	(rejected hunks)
Remove this file from the PR.

2021-03-08 04:03 UTC, julianrkung commented on src/lib/redux/siteData.ts
> +//refreshes the siteData in the background ie sets loading to false
We should instead just modify the `refreshSiteData` function so that we can pass in a `silent` or `background` parameter or something like that. We should probably determine if we show a loading screen depending on if it's silent or not (we should add another flag with an appropriate name), rather than if there's a `load` happening. 

This function should definitely just be merged to `refreshSiteData`, because they should effectively do the same thing.

2021-03-08 04:03 UTC, julianrkung commented on src/lib/redux/userData.ts
> +    if (state.userData.isOnline) {
Doesn't this function get run even if we aren't logged in? We'll get an empty `userData` and probably error out in that case. We want to only call `refreshDataBackground` if the user is currently logged in.

2021-03-08 04:03 UTC, julianrkung commented on src/lib/redux/userData.ts
> +      store.dispatch(setIsOnline({ isOnline: true }))
The `setIsOnline` doesn't have to be in the if statement since it'll be happening after it anyways right?

2021-03-13 07:16 UTC, julianrkung reviewed
Some comment deletes and a parameter rename and we should be good to merge! Thanks :)

2021-03-13 07:16 UTC, julianrkung commented on src/lib/redux/siteData.ts
> +
NIT: remove extra space

2021-03-13 07:16 UTC, julianrkung commented on src/lib/redux/userData.ts
> +        console.log("I AM REFRESHING")
NIT: remove log or make it lowercase and more professional like `background refresh occurring`

2021-03-13 07:16 UTC, julianrkung commented on src/lib/redux/userData.ts
> +// set interval is 15 min/900000 ms
NIT: Remove the `set interval is 15min/900000 ms` since it's not relevant to this function

2021-03-13 07:16 UTC, julianrkung commented on src/lib/redux/userData.ts
> +import { deauthenticateAndClearUserData, saveUserData, setIsOnline, setLoadingForUserData, } from './userDataSlice';
NIT: remove added comma in import

2021-03-13 07:16 UTC, julianrkung commented on package-lock.json
> -    "@reduxjs/toolkit": {
Would you mind doing a fresh `npm install` to see if this package-lock diff goes away? Kinda a NIT thing but it does make the diff look unclean so it'd be nice to fix if possible

2021-03-13 07:16 UTC, julianrkung commented on src/lib/redux/userData.ts
> +        //refresh data code here
Remove unnecessary comment

2021-03-13 07:16 UTC, julianrkung commented on src/lib/redux/userData.ts
> +      //refresh data code here
remove unnecessary comment

2021-03-13 07:16 UTC, julianrkung commented on src/lib/redux/siteData.ts
> +  //if background is true then dont set loading parameter.
`background` might not be the best name. Maybe `loadSilently` instead? The parameter name should indicate what it represents.

2021-03-17 05:36 UTC, kyleqhua commented on package-lock.json
> -    "@reduxjs/toolkit": {
does not go away

2021-03-17 16:46 UTC, julianrkung approved these changes
LGTM! Thanks!

2021-03-20 18:41 UTC, merged